### ISSUE TITLE
Not getting broadcaster badge pings

### ISSUE THREAD

**Issue by andw20** [itzAlex/chatterino7#6]
I have the broadcaster badge as a ping but it does not seem to work in the version 7.3.4H5
I just wanted to put it out there so the devs know. Not sure about the other badges but for broadcaster it does not work.

And I tried restarting and re-adding it as well and it should work because I went to another version (7.3.4 Nightly) and it 
seemed to work completely fine.

**Comment by itzAlex** [comment]
We are aware of a bug that causes user and badge highlights not to sound. Due to lack of time I won't be able to fix it soon, I hope you understand.

Thank you very much for reporting the bug :)
